import sys
sys.stdout.reconfigure(encoding='utf-8')

faq_html = """
    <details class="faq-item" id="faq-A316" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A316.</span><strong>A316.</strong> How do I select a discount rate / WACC for upstream investment committee analysis?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);background:var(--surface);">
        <p>Discount rate selection is the most consequential single assumption in an upstream IC model. ORCA reports government take and NPV sensitivity but does not mandate a WACC &mdash; that is the IC&rsquo;s responsibility. The standard upstream practice is a <strong>nominal, post-tax, project-level WACC</strong> applied to after-tax cash flows.</p>
        <p><strong>The four WACC inputs and their upstream calibration:</strong></p>
        <p>1. <strong>Risk-free rate:</strong> Use the 10-year US Treasury yield (USD-denominated projects) or the host-country sovereign bond yield for local-currency projects. As of mid-2026, the US 10-year yield is approximately 4.5%. Avoid using short-term rates &mdash; upstream project life typically spans 15&ndash;30 years.</p>
        <p>2. <strong>Equity risk premium (ERP):</strong> A standard global ERP is 5&ndash;6% (Damodaran estimates). For frontier markets (Sub-Saharan Africa, Central Asia, certain LATAM countries), add a country risk premium (CRP) of 2&ndash;8% depending on sovereign credit rating, political stability, and currency risk. Nigeria: +5&ndash;6%; Angola: +4&ndash;5%; Kazakhstan: +2&ndash;3%; Norway: +0%.</p>
        <p>3. <strong>Upstream beta:</strong> Unlevered betas for E&amp;P companies cluster around 0.9&ndash;1.2. For a single-asset IC analysis, use a project-specific risk premium overlay rather than a beta: add 2&ndash;5pp to the corporate WACC for exploration-stage assets, 0&ndash;1pp for production assets with offtake contracted.</p>
        <p>4. <strong>Capital structure and tax shield:</strong> Upstream projects are typically modeled on a project-financed or all-equity basis for IC purposes (to keep the IC clean of financing assumptions). If the project carries debt, tax-shield the interest at the host-country corporate tax rate and use a WACC that reflects the after-tax cost of debt.</p>
        <p><strong>Typical upstream discount rate benchmarks by asset type:</strong> OECD conventional: 8&ndash;10%; Emerging market conventional: 10&ndash;14%; Deepwater frontier: 12&ndash;16%; LNG greenfield: 8&ndash;12% (lower due to long-term offtake); Arctic / ultra-deepwater: 15&ndash;20%.</p>
        <p><strong>Rule of thumb:</strong> If your ORCA NPV10 is marginally positive (NPV10/investment &lt; 0.2), the project does not clear the bar for most major IOC investment criteria. A robust project at fair risk adjustment should show NPV10/investment &gt; 0.4 before fiscal risk haircuts.</p>
        <p><strong>Source:</strong> ORCA v317 (Aug 2026). Damodaran Country Risk Premium dataset (Jan 2026); SPE-209990-MS (WACC calibration for upstream project economics); Wood Mackenzie Upstream Toolkit WACC guidance; BP Capital Allocation Framework public disclosures. Cross-references: FAQ A1 (what ORCA NPV represents); FAQ A48 (sensitivity conventions); FAQ A95 (government take vs. NPV relationship).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A317" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A317.</span><strong>A317.</strong> What is the fiscal cliff in PSC term expiry, and how do I model it?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);background:var(--surface);">
        <p>A <strong>fiscal cliff</strong> occurs when a PSC contract expires while production is still ongoing and the contractor has not secured a renegotiation or extension. At expiry, the contractor&rsquo;s entitlement to production &mdash; and revenue &mdash; falls to zero (or near-zero, depending on whether a short-term operating agreement is in place). The cliff is distinct from normal production decline: it is a <em>contractual</em> truncation of cash flow, not a geological one.</p>
        <p><strong>Why this matters for IC:</strong> Late-life PSC assets with 3&ndash;7 years of contract life remaining are systematically under-valued by models that assume perpetual entitlement. The fiscal cliff creates a hard discount &mdash; any NPV that relies on cash flows beyond contract expiry carries binary risk. IC memos must state the contract expiry date and quantify production volume at risk.</p>
        <p><strong>How to model the cliff in ORCA Scenario Builder:</strong> Set the project plateau and decline to match remaining contract life only. Do not extend production profile beyond contract expiry unless you have documentary evidence of a renewal offer or extension agreement. Run a secondary scenario at expiry +5 years (assuming successful extension at renegotiated terms) and explicitly note the assumption delta between the two scenarios in your IC memo.</p>
        <p><strong>Common renegotiation triggers:</strong> (1) NOC cash need &mdash; host government prefers extension at slightly better terms over rebidding; (2) Contractor investment commitment &mdash; host accepts extension in exchange for a new development well commitment or facility investment; (3) Contractor relinquishment &mdash; late-life assets in frontier zones are sometimes relinquished voluntarily to avoid abandonment liability.</p>
        <p><strong>Countries with frequent PSC cliff risk:</strong> Angola (most PSCs expire 2027&ndash;2032 without formal extension agreements as of 2026); Indonesia (multiple mature PSC blocks, KKKS system tracks expirations); Vietnam (Blocks 05-2, 05-3 expiry discussions active); Egypt (expiries negotiated case-by-case via EGPC).</p>
        <p><strong>Rule of thumb:</strong> Discount PSC cash flows beyond year 20 from first oil by an additional 15&ndash;25% for cliff risk unless a specific extension commitment exists in writing. For assets within 5 years of expiry, apply a binary scenario tree: P50 extension probability 60% at similar terms, 40% hard stop.</p>
        <p><strong>Source:</strong> ORCA v317 (Aug 2026). Angola Ministry of Mineral Resources / ANPG Block expiry schedule (2026); Indonesia SKK Migas Contract Status Register; Vietnam PetroVietnam Block Licenses report; Wood Mackenzie PSC Expiry Risk Monitor. Cross-references: FAQ A14 (PSC basics); FAQ A37 (contract renegotiation risk); FAQ A112 (Angola fiscal regime).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A318" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A318.</span><strong>A318.</strong> How do shallow water and deepwater fiscal regimes differ, and what does that mean for IC economics?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);background:var(--surface);">
        <p>Shallow water (&lt;500m) and deepwater (&gt;500m, ultra-deepwater &gt;1,500m) typically operate under different fiscal terms in the same country, reflecting the host government&rsquo;s recognition that deepwater carries higher capital intensity, technical risk, and longer cycle time. The fiscal gap is widest in Africa and LATAM, where governments introduced deepwater-specific PSCs in the 1990s&ndash;2000s to attract IOC capital for frontier exploration.</p>
        <p><strong>Typical fiscal differentiation mechanisms:</strong></p>
        <p><strong>1. Royalty waiver or reduction:</strong> Many countries exempt deepwater blocks from surface royalties (Nigeria: no royalty &lt;200m water depth; Brazil: reduced royalty 5% vs 10&ndash;15% shallow; Mozambique: reduced royalty in deepwater blocks). This is the largest single take differential.</p>
        <p><strong>2. Cost recovery ceiling:</strong> Deepwater PSCs typically allow higher cost recovery ceilings (80&ndash;90% vs 60&ndash;70% shallow), recognizing the capex intensity of subsea development.</p>
        <p><strong>3. Profit oil split:</strong> Deepwater profit oil splits are generally more contractor-favorable, especially at early production tranches, to incentivize exploration. Angola Block 15 (deepwater) has substantially more contractor-favorable terms than the original onshore/shallow-water Sonangol PSCs from the 1970s&ndash;80s.</p>
        <p><strong>4. Investment credit:</strong> Some countries (Nigeria, Azerbaijan historical) provide an upfront investment tax credit for deepwater capex that does not exist for shallow-water projects.</p>
        <p><strong>ORCA representation:</strong> ORCA&rsquo;s Country Profile shows the primary regime type. Where a country has both shallow and deepwater regimes with distinct terms, ORCA includes both in the Fiscal Compare tool. Look for the water depth qualifier in the regime name (e.g., &ldquo;Nigeria &mdash; PSC Deepwater (Blocks 200+)&rdquo; vs. &ldquo;Nigeria &mdash; PSC (Shallow/JV)&rdquo;).</p>
        <p><strong>IC implication:</strong> For a deepwater IC analysis, confirm you are using the deepwater-specific fiscal terms. Using shallow-water terms for a deepwater project will overstate government take by 10&ndash;20pp in most African regimes &mdash; a material IC error.</p>
        <p><strong>Rule of thumb:</strong> In Africa and LATAM, deepwater government take is typically 5&ndash;15pp lower than shallow-water take in the same country. In the North Sea (UK/Norway), the differential is smaller because all offshore is effectively deepwater by global standards and a single fiscal regime applies.</p>
        <p><strong>Source:</strong> ORCA v317 (Aug 2026). Nigeria DPR Fiscal Terms Guide (2020); Brazil ANP Concession and PSC Terms; Mozambique INP Model PSA deepwater schedule; Angola ANPG deepwater block terms. Cross-references: FAQ A60 (Nigeria shallow vs. deepwater); FAQ A200 (Brazil pre-salt fiscal); FAQ A304 (Indonesia deepwater).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A319" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A319.</span><strong>A319.</strong> How do Iraq Kurdistan Region (KRG) fiscal terms compare to Federal Iraq PSC terms?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);background:var(--surface);">
        <p>Iraq-Kurdistan and Federal Iraq operate under fundamentally different fiscal and legal frameworks, despite both being in Iraqi territory. This distinction is critical for IC analysis &mdash; an IC memo that treats &ldquo;Iraq&rdquo; as a single fiscal regime is materially wrong.</p>
        <p><strong>Federal Iraq (Baghdad government):</strong> Uses Technical Service Contracts (TSC) / Remuneration Fee contracts, not PSCs. IOCs receive a fixed remuneration fee per barrel produced (historically $1.15&ndash;$2.00/bbl, varying by contract round). IOCs bear development costs but have no equity interest in reserves. Government take under TSC is extremely high &mdash; often 85&ndash;95%+ at moderate prices. Federal Iraq is a fee-for-service model, not a risk/reward partnership. IOCs participate for volume exposure and balance sheet booking (subject to SPE reserve recognition criteria), not for fiscal upside.</p>
        <p><strong>Kurdistan Region of Iraq (KRG):</strong> Uses PSCs governed by Kurdistan&rsquo;s own petroleum law (Law 22 of 2007). KRG PSCs include: production royalty (10%), cost recovery (typically 40% ceiling), profit oil split (varying from 20/80 contractor/KRG at low production to higher contractor share at exploration-stage), and income tax exemption for the first 10 years. ORCA models KRG PSCs as distinct from Federal Iraq TSCs. KRG government take is materially lower than Federal Iraq &mdash; typically 60&ndash;75% vs. 85&ndash;95% federal.</p>
        <p><strong>The key legal dispute:</strong> Federal Baghdad does not recognize KRG&rsquo;s authority to sign PSCs independently with IOCs, and disputes export rights over KRG crude (historically routed via Turkey/Ceyhan pipeline). KRG IOCs (DNO, Genel, Gulf Keystone) face a dual risk: fiscal attractiveness at KRG terms but sovereign risk of Baghdad intervention. This legal overhang must appear in any IC memo covering a KRG asset.</p>
        <p><strong>ORCA coverage:</strong> ORCA includes KRG PSC model terms and Federal Iraq TSC terms as separate regime entries. Use &ldquo;Iraq-KRG&rdquo; for Kurdistan assets; use &ldquo;Iraq&rdquo; for Basra/southern field service contracts. Do not blend these in a single IC scenario.</p>
        <p><strong>Rule of thumb:</strong> KRG PSC take at $75/bbl is approximately 65&ndash;70%. Federal Iraq TSC effective take (fee + royalty) is approximately 90&ndash;93% at $75/bbl &mdash; making Federal Iraq one of the highest-take regimes globally.</p>
        <p><strong>Source:</strong> ORCA v317 (Aug 2026). Kurdistan Region Law 22 of 2007 (Petroleum Law); Federal Iraq Bid Round 2 and 4 TSC terms; DNO ASA Annual Report 2025; Genel Energy Annual Report 2025; Gulf Keystone Petroleum Annual Report 2025. Cross-references: FAQ A66 (Iraq Federal TSC mechanics); FAQ A67 (KRG PSC structure); FAQ A290 (Middle East fiscal landscape).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A320" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A320.</span><strong>A320.</strong> What is the African Atlantic margin frontier landscape and how do I approach IC analysis for it?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);background:var(--surface);">
        <p>The African Atlantic margin &mdash; running from Mauritania and Senegal in the northwest through West Africa (Guinea-Bissau, Guinea, Sierra Leone, Liberia, Ivory Coast, Ghana, Togo, Benin, Nigeria, Cameroon, Equatorial Guinea, Gabon, Congo, DRC, Angola) and extending south to Namibia and South Africa &mdash; is one of the highest-activity frontier exploration zones globally as of 2025&ndash;2026, driven by a combination of proven analog plays from established provinces and several transformative recent discoveries.</p>
        <p><strong>The Namibia-South Africa breakout:</strong> TotalEnergies&rsquo; Orange Basin discoveries (Venus, 2022; Graff, 2022) offshore Namibia represent one of the largest frontier finds in a decade. Shell&rsquo;s South Africa Brulpadda and Luiperd discoveries (Outeniqua Basin) added another data point. These have catalyzed a new round of Atlantic margin reprocessing and refarming activity that extends the opportunity set from the established West Africa core northward and southward.</p>
        <p><strong>Frontier fiscal caution:</strong> Frontier Atlantic margin regimes often have immature fiscal frameworks &mdash; terms are set by early-exploration model PSCs that may be renegotiated as commercial discoveries mature. Namibia&rsquo;s fiscal terms (EPE Model PSA) are still being finalized for commercial development following the Venus discovery. South Africa has a concessionary regime (petroleum rights) that has not been tested by a major development project. IC analysis for frontier Atlantic margin assets must explicitly flag fiscal framework immaturity as a risk factor and scenario-test against a range of likely post-discovery renegotiated terms.</p>
        <p><strong>Established vs. frontier segments:</strong> Nigeria, Angola, Gabon &mdash; established regimes, mature terms, ORCA data is reliable. Senegal/Mauritania (Sangomar, GTA) &mdash; terms finalized and first LNG online (2024 Tortue); ORCA has model terms. Namibia/South Africa &mdash; terms still evolving; ORCA provides indicative terms only (flagged as provisional in Country Profile).</p>
        <p><strong>Rule of thumb:</strong> For established Atlantic margin (Nigeria, Angola, Gabon), ORCA terms are reliable for IC. For frontier Atlantic margin (Namibia, South Africa, Sierra Leone, Liberia), add a +5pp take risk buffer to the ORCA base case and scenario-test at +10pp (renegotiation risk) in the IC sensitivity table.</p>
        <p><strong>Source:</strong> ORCA v317 (Aug 2026). TotalEnergies Orange Basin exploration reports (2022&ndash;2026); Wood Mackenzie Namibia Deepwater Outlook (2025); EPE Namibia Model PSA (draft 2025); South Africa DMRE Petroleum Rights Act guidance; Rystad Energy Sub-Saharan Africa Exploration Atlas. Cross-references: FAQ A112 (Angola); FAQ A76 (Nigeria deepwater); FAQ A118 (Senegal/Mauritania Tortue); FAQ A200 (frontier regime risk).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A321" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A321.</span><strong>A321.</strong> How do South American bid round strategies differ across countries, and what should an IC model capture?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);background:var(--surface);">
        <p>South America hosts four distinct bid round cultures and fiscal models. Conflating them in an IC memo is a credibility risk.</p>
        <p><strong>Brazil (ANP):</strong> The world&rsquo;s most technically sophisticated bid round operator. Two fiscal tracks run in parallel: (1) Concession rounds (traditional, oil-and-gas rights, sliding-scale royalties 5&ndash;40%, open to all IOCs); (2) Production Sharing rounds (pre-salt Polygon, Petrobras as mandatory operator with 30% minimum stake, profit oil bid parameter &mdash; IOCs bid the percentage of profit oil they offer to the government above the minimum). Pre-salt IC analysis requires modeling the Petrobras carry and the government&rsquo;s pre-salt profit oil share on top of the concession royalty layer.</p>
        <p><strong>Guyana (EPA-Guyana / EEPGL):</strong> Not an open bid round country &mdash; the Stabroek Block was awarded via direct negotiation in 1999 under terms that are now widely regarded as contractor-favorable (2% royalty, 75% cost recovery ceiling, 50/50 profit oil split). There is no active bid round as of 2026. New blocks (Canje, Kaieteur, Beebei-Potaro) have been awarded bilaterally. IC analysis must use actual block-specific PSC terms from EPA-Guyana filings, not model terms.</p>
        <p><strong>Argentina (Vaca Muerta / MINEM rounds):</strong> Primarily a concession regime. Bid rounds for Vaca Muerta unconventional blocks are provincially administered (Neuqu&eacute;n province), not federal. Royalty rates are fixed by province (12% federal base, negotiable additional province royalty). IOCs must negotiate with both MINEM (federal) and the relevant provincial authority. Fiscal stability agreements (estabilidad fiscal) are critical &mdash; Argentina&rsquo;s history of retroactive fiscal changes makes stability clause language a primary IC risk factor.</p>
        <p><strong>Colombia (ANH rounds):</strong> Open competitive bid rounds administered by ANH. Concession regime with sliding-scale royalties (8&ndash;25%) and high-price participation mechanism (ANH takes incremental revenue above a threshold price). Colombia&rsquo;s high-price mechanism is frequently overlooked in IC analysis &mdash; it materially reduces contractor economics at oil prices above $80/bbl. ORCA models this mechanism in the Colombia fiscal entry.</p>
        <p><strong>Rule of thumb:</strong> For any South America IC, identify the administering authority (federal vs. provincial), the bid parameter that was competitively submitted (profit oil %, work program commitment, or bonus), and whether a fiscal stability clause exists. Stability clause absence in Argentina is an automatic IC risk flag.</p>
        <p><strong>Source:</strong> ORCA v317 (Aug 2026). Brazil ANP Rodada records (R1&ndash;R17); EPA-Guyana Block License Terms (Stabroek, Canje); Argentina MINEM / Neuqu&eacute;n Province Concession Register; Colombia ANH Bid Round 2024 Terms. Cross-references: FAQ A155 (Brazil pre-salt fiscal); FAQ A160 (Guyana Stabroek terms); FAQ A170 (Colombia ANH mechanism).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A322" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A322.</span><strong>A322.</strong> What is the fiscal impact of plateau extension and how do I model it?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);background:var(--surface);">
        <p>Plateau extension &mdash; drilling infill wells or adding compression to maintain production at peak rate for additional years before the natural decline sets in &mdash; is one of the highest-NPV capital allocation decisions in upstream. The fiscal impact is significant: extending plateau keeps the project in a cost-recovery-advantaged or low-profit-oil tranche longer, delaying the point at which the government&rsquo;s higher profit oil share kicks in.</p>
        <p><strong>The fiscal interaction:</strong> In PSC regimes with a production-tranche profit oil split, the split step-up is usually triggered by daily production crossing a threshold (e.g., contractor share drops from 60% to 40% at &gt;50,000 bbl/d). Plateau extension at 48,000 bbl/d (just below the step-up trigger) maximizes contractor profit oil fraction. In concession regimes with sliding-scale royalties (Brazil, Norway, US deepwater), plateau extension at high production rates keeps royalty rates elevated &mdash; but this is partially offset by the incremental production volume.</p>
        <p><strong>IC modeling approach:</strong> Run two scenarios: (A) natural decline without infill investment; (B) plateau extension with incremental capex commitment. Calculate the incremental NPV of (B) vs. (A) at the project WACC. The fiscal benefit of plateau extension (lower effective take during extended plateau period) is a real component of the NPV uplift &mdash; it should be itemized separately in the IC memo alongside the production volume uplift.</p>
        <p><strong>Using ORCA Scenario Builder for plateau extension:</strong> Model the project twice &mdash; once with the original plateau profile (peak rate, plateau years, decline rate) and once with the extended plateau (same peak rate, +3 years plateau, same decline). Compare government take% across both scenarios. In most PSC regimes with profit oil tranches, take% will be 1&ndash;5pp lower during the extension period because the project remains in a more contractor-favorable tranche longer.</p>
        <p><strong>Rule of thumb:</strong> In production-tranche PSC regimes, every additional year of plateau at or below the step-up threshold is worth 1&ndash;3% additional contractor NPV vs. the equivalent year of declining production. Quantify this in the IC sensitivity table as &ldquo;Plateau extension fiscal benefit: +X% NPV.&rdquo;</p>
        <p><strong>Source:</strong> ORCA v317 (Aug 2026). SPE-210046-MS (infill drilling NPV in PSC regimes); Wood Mackenzie Plateau Extension Economics Handbook; IEA Upstream Technology and Well Productivity Report 2025; Shell Annual Report 2025 (plateau maintenance capex allocation). Cross-references: FAQ A48 (NPV sensitivity conventions); FAQ A316 (WACC selection); FAQ A95 (take vs. NPV relationship).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A323" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A323.</span><strong>A323.</strong> How does the EU Carbon Border Adjustment Mechanism (CBAM) interact with upstream fiscal terms?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);background:var(--surface);">
        <p>The EU Carbon Border Adjustment Mechanism (CBAM) entered its transitional phase in October 2023 and is scheduled to reach full implementation by January 2026 (later delayed to 2027). CBAM initially targets cement, steel, aluminum, fertilizers, electricity, and hydrogen &mdash; not crude oil or LNG directly. However, the interaction with upstream fiscal analysis is increasingly relevant for three pathways:</p>
        <p><strong>Pathway 1 &mdash; Refined products and downstream feedstock:</strong> CBAM applies to carbon embedded in goods crossing the EU border. Crude oil refined in a non-EU country and then exported to the EU as a refined product is outside CBAM&rsquo;s current scope. However, petrochemical feedstocks (including hydrogen and ammonia derived from natural gas) are in scope. LNG-to-hydrogen projects for EU export face CBAM exposure on the hydrogen output &mdash; this is an emerging cost item for greenfield FSRU-to-hydrogen projects in North Africa and East Mediterranean targeting EU markets.</p>
        <p><strong>Pathway 2 &mdash; Methane emissions and GHG-adjusted fiscal baselines:</strong> Several European oil majors (BP, Shell, TotalEnergies) now apply an internal carbon price ($40&ndash;$80/tCO2e) to upstream investment decisions. This effectively increases the cost of high-GHG assets (flaring-heavy operations, high-emission gas fields) and reduces their post-carbon-price NPV. ORCA does not apply a GHG adjustment to fiscal take &mdash; but IC memos for EU-headquartered IOCs should add a carbon cost overlay to the ORCA base case.</p>
        <p><strong>Pathway 3 &mdash; Host country fiscal reform pressure:</strong> CBAM creates indirect pressure on producing countries to introduce carbon pricing to avoid the &ldquo;carbon leakage&rdquo; framing that CBAM addresses. Countries exporting to EU-adjacent markets may internalize carbon costs via new petroleum levies or revised fiscal terms. This is a medium-term fiscal risk (3&ndash;7 year horizon) that belongs in the IC political risk section, not the base-case fiscal model.</p>
        <p><strong>ORCA&rsquo;s position:</strong> ORCA fiscal terms do not incorporate carbon pricing unless the host country has a formal carbon tax applied to upstream operations (currently: Norway&rsquo;s CO2 tax is modeled; EU ETS exposure for upstream is not separately modeled). Users should add carbon cost overlays manually for CBAM-exposed projects.</p>
        <p><strong>Rule of thumb:</strong> For projects targeting EU markets (North Africa gas, East Mediterranean LNG, West Africa LNG), add a carbon cost sensitivity of $30&ndash;$50/tCO2e applied to the project&rsquo;s methane intensity (tCO2e/bbl equivalent) to stress-test the IC scenario. For OECD-producing assets (Norway, UK, Canada), the carbon cost is already partially internalized via existing carbon taxes &mdash; verify against ORCA&rsquo;s country-specific tax model.</p>
        <p><strong>Source:</strong> ORCA v317 (Aug 2026). EU CBAM Regulation (EU) 2023/956; European Commission CBAM Implementation Guidance (2024); IEA Net Zero Roadmap 2023; Shell Sky Scenario carbon price trajectory; TotalEnergies Internal Carbon Price Disclosure 2025. Cross-references: FAQ A248 (Norway carbon tax); FAQ A302 (energy transition fiscal risk); FAQ A260 (UK upstream carbon pricing).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A324" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A324.</span><strong>A324.</strong> What are the key features of Caspian PSA structures, and how do they differ from West African PSCs?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);background:var(--surface);">
        <p>Caspian Basin Production Sharing Agreements (PSAs) &mdash; primarily in Azerbaijan, Kazakhstan, and Turkmenistan &mdash; are among the most complex and contractor-favorable upstream fiscal arrangements ever negotiated. They were designed in the 1990s to attract IOC capital to a region with no functioning legal system, no convertible currency, and high political risk. The result is a class of contracts that are exceptionally well-documented, heavily negotiated, and often more contractor-favorable than any currently available term globally.</p>
        <p><strong>Azerbaijan (AIOC / ACG PSA):</strong> The ACG (Azeri-Chirag-Gunashli) PSA signed in 1994 is the template. Key features: (1) No income tax &mdash; replaced by a profit petroleum share; (2) Cost recovery of 100% of eligible costs against cost petroleum (no ceiling); (3) Profit petroleum split highly contractor-favorable at low production tranches; (4) &ldquo;Oil bonus&rdquo; trigger payments; (5) Stabilization clause &mdash; fiscal terms freeze at signing date, immune to subsequent Azerbaijani tax law changes; (6) International arbitration (ICC/ICSID). BP operates ACG with a 30.37% interest. The PSA runs to 2049 (extended).</p>
        <p><strong>Kazakhstan (Tengiz / Kashagan TCO/NCOC agreements):</strong> Tengizchevroil (TCO) operates under a joint venture agreement (1993), not a formal PSA, but with PSA-equivalent fiscal terms: production sharing, cost recovery, stabilized tax rates. Kashagan (North Caspian Operating Company, NCOC) is a PSA with additional complexity: a cost overrun renegotiation in 2008 shifted terms toward the host government (KazMunayGas increased its share) &mdash; a rare precedent of contractual renegotiation under force of circumstance rather than formal arbitration.</p>
        <p><strong>Key differences from West Africa PSCs:</strong> (1) Caspian PSAs typically have no royalty (or trivially small royalty); West Africa PSCs typically have a 5&ndash;15% royalty or equivalent production levy. (2) Caspian PSAs are project-specific, bespoke agreements negotiated contract-by-contract; West Africa PSCs follow a model form with bid parameters. (3) Caspian cost recovery is typically 100% or near-100% with no ceiling; West Africa cost recovery ceilings are commonly 60&ndash;80%. (4) Caspian stabilization clauses are absolute; West Africa model PSCs often have &ldquo;economic equilibrium&rdquo; renegotiation clauses that allow host government to seek rebalancing.</p>
        <p><strong>ORCA coverage:</strong> ORCA models ACG/Azerbaijan terms and Kazakhstan Tengiz/Kashagan model terms separately. Use the country-specific regime entry rather than a generic PSC template &mdash; Caspian contracts diverge substantially from the West Africa PSC model.</p>
        <p><strong>Rule of thumb:</strong> Caspian government take at $75/bbl is typically 55&ndash;65% &mdash; lower than comparable West African deepwater (65&ndash;75%) due to no royalty and 100% cost recovery. However, the geopolitical/infrastructure risk premium (landlocked basin, pipeline dependency, Russia/Iran adjacency) partially offsets the fiscal advantage in any IC risk-adjusted comparison.</p>
        <p><strong>Source:</strong> ORCA v317 (Aug 2026). AIOC ACG PSA (1994, publicly available via EITI Azerbaijan); TCO Joint Venture Agreement summary (Chevron public disclosures); NCOC Kashagan PSA renegotiation terms (KazMunayGas 2008); BP Annual Report 2025 (ACG operational update). Cross-references: FAQ A130 (Azerbaijan fiscal); FAQ A135 (Kazakhstan fiscal); FAQ A37 (contract stability risk).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A325" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A325.</span><strong>A325.</strong> How do I assess ORCA data vintage gaps &mdash; when is the data current enough for IC, and when do I need to verify independently?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);background:var(--surface);">
        <p>ORCA data has a vintage &mdash; fiscal terms are researched, verified, and entered as of a specific date. The platform undergoes structured harvesting cycles (typically weekly to monthly) and publishes a vintage date per-country in the Country Profile source confidence section. Understanding what is current vs. what is stale is essential to using the platform responsibly in IC work.</p>
        <p><strong>How to assess vintage adequacy:</strong></p>
        <p><strong>1. Check the source confidence badge (A/B/C tier):</strong> The badge in each Country Profile summarizes data quality. Tier A = verified primary source (model PSA/concession agreement, official gazette, government publication) within 24 months. Tier B = secondary source or &gt;24 months since last primary verification. Tier C = proxy/analog estimate, no primary source. For IC use, Tier C data requires independent verification before citation.</p>
        <p><strong>2. High-risk vintage gap categories:</strong> (a) Resource windfall/excess profit taxes &mdash; these are the terms most frequently changed by governments in high-price environments. Verify against the host country&rsquo;s official tax authority or petroleum regulator for any country where oil was above $80/bbl for &gt;6 months. (b) Royalty rate schedules &mdash; sliding-scale royalties change frequently (Nigeria DPR has updated its royalty schedule 3 times since 2018). (c) New block licensing rounds &mdash; any block awarded in the last 18 months may have bid terms not yet reflected in ORCA. Check ANP, DPR, or host NOC announcements.</p>
        <p><strong>3. Stable vs. volatile data categories:</strong> Stable (safe to rely on without re-verification for 3&ndash;5 years): fundamental regime type (concession vs. PSC vs. TSC), income tax rate on petroleum income, cost recovery ceiling. Volatile (re-verify annually or for any current IC): royalty rate at current production volume, profit oil split at current price, excess profit tax threshold, any terms introduced post-2022 (energy transition / windfall context).</p>
        <p><strong>4. How to cite ORCA responsibly in IC memos when data vintage is uncertain:</strong> Add a footnote: &ldquo;ORCA v317 (Aug 2026) terms used as baseline; [country name] [specific term] not independently verified against [regulator] as of IC date. Recommend validation against [source] before investment committee sign-off.&rdquo; This is the correct professional posture &mdash; ORCA is a baseline tool, not a substitute for primary research on material inputs.</p>
        <p><strong>Rule of thumb:</strong> For any country where government take is &gt;75% (high-take regime), a 5pp error in a volatile term (royalty, profit oil) translates to a significant NPV impact. High-take regimes warrant higher verification investment. For regimes where government take is &lt;60%, the same 5pp error is less material &mdash; ORCA data is likely sufficient for IC without re-verification.</p>
        <p><strong>Source:</strong> ORCA v317 (Aug 2026). EITI country-by-country fiscal data (2024 update); host country petroleum regulator websites (primary); Wood Mackenzie Fiscal Data Vintage Disclosure Policy; Rystad Energy Upstream Fiscal Terms Verification Protocol. Cross-references: FAQ A1 (what ORCA is and is not); FAQ A2 (data confidence and source hierarchy); FAQ A298 (IC memo disclosure template).</p>
      </div>
    </details>
"""

with open('C:/Users/ztuch/petroleum-fiscal-db/index.html', 'r', encoding='utf-8') as f:
    content = f.read()

back_to_top = '    <div style="text-align:right;margin-top:16px;padding-top:10px;border-top:1px solid var(--border);">\n      <a href="#tab-btn-tmeth"'

pos = content.find(back_to_top)
if pos == -1:
    print('ERROR: back-to-top div not found')
else:
    print(f'Found back-to-top at position {pos}')
    content = content[:pos] + faq_html + '\n' + content[pos:]
    with open('C:/Users/ztuch/petroleum-fiscal-db/index.html', 'w', encoding='utf-8') as f:
        f.write(content)
    print('FAQs A316-A325 inserted successfully')
    print(f'New file size: {len(content)} chars')
