#!/usr/bin/env python3
"""Cycle 282 patch: Insert FAQs A471-A480 and do v355->v356 structural sweep."""

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

print(f"Original length: {len(content)}, v355 count: {content.count('v355')}")

# ── FAQ A471-A480 content ──
faq_new = '''
        <div class="faq-item" id="faq-A471">
          <div class="faq-q">A471. How does gas monetization route selection (LNG export vs. pipeline export vs. domestic sale vs. reinjection) affect the effective fiscal take computed by ORCA, and what IC adjustment workflow should an analyst use when evaluating a gas-prone exploration block?</div>
          <div class="faq-a">
            <p>Gas monetization route is one of the most consequential fiscal variables for gas-prone exploration, yet ORCA&rsquo;s government take figures are computed on a standardized oil production profile ($75/bbl Brent) that does not differentiate by gas route. For blocks with significant associated or non-associated gas, the analyst must overlay a gas monetization adjustment on top of ORCA&rsquo;s oil-proxy take figure.</p>
            <p><strong>Route 1 &mdash; LNG export (toll-liquefied or equity):</strong> Typically the highest-value route for remote gas. Upstream fiscal terms apply to wellhead gas production (royalty, profit gas, CIT). Midstream LNG fiscal layer adds liquefaction CIT, export levy (where imposed), and WHT on LNG dividends. Wellhead netback price = FOB LNG price minus liquefaction opex ($2.5&ndash;4/MMBtu) minus shipping ($0.5&ndash;1.5/MMBtu) minus marketing margin. For JCC-linked contracts at $75/bbl Brent: wellhead netback approximately $5.5&ndash;7/MMBtu. IC adjustment: if ORCA take is calibrated at $75/bbl oil, the effective upstream revenue is reduced by 30&ndash;50% relative to oil &mdash; reduce NPV proportionally but apply the same take%. Rule of thumb: for PSC gas monetization via LNG, add 5&ndash;10pp integrated take vs. oil-only ORCA figure (upstream + liquefaction layer).</p>
            <p><strong>Route 2 &mdash; Pipeline export:</strong> Higher value than domestic sale, lower than LNG for most markets. Royalty and CIT apply at the export metering point. Hub-linked pricing (Henry Hub, NBP, TTF) adds de-correlation risk from Brent. For regimes where royalty is ad valorem on wellhead price, pipeline export pricing directly reduces royalty burden vs. LNG-equivalent volumes. Rule of thumb: pipeline export take approximately 0&ndash;3pp below LNG-export effective take at the same statutory terms.</p>
            <p><strong>Route 3 &mdash; Domestic sale / DMO:</strong> Most gas-producing PSC regimes impose a domestic market obligation (DMO) requiring a fraction (5&ndash;25%) of contractor entitlement gas to be sold domestically at regulated below-market prices. Indonesia: DMO gas priced at $3&ndash;5/MMBtu vs. LNG export $8&ndash;10/MMBtu. Nigeria: domestic gas obligation at $3.5/MMBtu vs. export $7&ndash;9/MMBtu. IC adjustment: for each 10% of production under DMO at half export price, add approximately 0.8&ndash;1.5pp effective take. Full DMO regimes (all gas must be sold domestically) can add 5&ndash;10pp effective take vs. export-equivalent take.</p>
            <p><strong>Route 4 &mdash; Reinjection (pressure maintenance / EOR):</strong> Reinjected volumes generate no export revenue. Fiscal treatment varies: Concession &mdash; reinjected gas is typically excluded from royalty computation (no revenue generated). PSC &mdash; reinjected gas may be excluded from profit gas computation but the reinjection capex is cost-oil eligible. Gross Split Indonesia &mdash; EOR reinjection may trigger an additional variable split component of +2&ndash;5pp contractor share on remaining production. Gas later re-produced when reinjection ceases is typically metered as new gross production and subject to full royalty/profit gas treatment.</p>
            <p><strong>IC workflow &mdash; gas monetization adjustment:</strong> Step 1 &mdash; identify gas route from block license / IOC operator disclosure. Step 2 &mdash; apply ORCA upstream take at Deepwater or appropriate profile. Step 3 &mdash; overlay gas route adjustment: LNG +5&ndash;10pp integrated, pipeline +0&ndash;3pp, DMO +0.8&ndash;1.5pp per 10% volume, reinjection 0pp (no revenue). Step 4 &mdash; IC memo disclosure: &ldquo;ORCA upstream take [X]%. Gas monetization route [LNG/pipeline/domestic/reinjection]. Integrated effective take estimated [Y]% including [adjustments applied]. Source: ORCA v356 + analyst overlay.&rdquo;</p>
            <p><em>Source: ORCA Petroleum Fiscal Intelligence Platform v356 (Aug 2026), yoburgqs.github.io/petroleum-fiscal-db/. Cross-references: FAQ A462 (associated gas PSC fiscal pathways), FAQ A467 (gas reinjection fiscal treatment), FAQ A469 (integrated LNG fiscal modeling), FAQ A441 (gas monetization route selection &mdash; original framework).</em></p>
          </div>
        </div>

        <div class="faq-item" id="faq-A472">
          <div class="faq-q">A472. What is associated gas fiscal treatment in a Concession regime, and how does the decision to flare, reinject, or sell associated gas affect the net IRR of an oil-primary development project?</div>
          <div class="faq-a">
            <p>Associated gas (AG) is natural gas produced alongside crude oil in oil-primary fields. In Concession regimes, the fiscal treatment of associated gas differs materially from non-associated gas developments and is rarely captured in ORCA&rsquo;s standardized oil-production model. The three disposal routes &mdash; flaring, reinjection, and sales &mdash; each carry distinct fiscal consequences that can shift net project IRR by 1&ndash;4 percentage points.</p>
            <p><strong>Flaring (disposal, no revenue):</strong> Most Concession regimes now impose anti-flaring penalties that convert associated gas from a zero-revenue stream into a net cost. Nigeria: flaring penalty $3.50/Mscf under the Petroleum Industry Act (2021) &mdash; for a field producing 20 MMscf/d of associated gas, the annual flaring penalty is $25.5M, which is CIT-deductible but still a direct cost. Algeria: flaring fined at $0.5/Mscf but volume ceilings apply. US Gulf of Mexico: royalty is waived on flared gas but EPA enforcement adds a shadow cost. IC adjustment: add $0.5&ndash;3.5/Mscf as a non-cost-recoverable burden. For a mid-size field with 15 MMscf/d associated gas over 20 years, the cumulative penalty is $130&ndash;380M &mdash; a 0.8&ndash;2.0pp IRR drag depending on flare volume.</p>
            <p><strong>Reinjection (pressure maintenance):</strong> Concession regimes typically allow CIT deduction of reinjection capex and opex. Royalty is not charged on reinjected volumes (no sales revenue). Capital cost of reinjection compressors and pipelines ($50&ndash;150M for a mid-size project) is recoverable. When reinjection gas is later re-produced as solution gas in oil production, it is metered with oil and subject to royalty on the composite stream. Net fiscal effect: reinjection is typically IRR-neutral to slightly positive vs. flaring (capex deductible, no penalty, future production recovery benefit) but negative vs. full monetization. IC rule of thumb: reinjection vs. flaring = +0.3&ndash;0.8pp IRR for the oil project (penalty avoided, capex deductible).</p>
            <p><strong>Sales (pipeline or LNG):</strong> Generates revenue subject to royalty, CIT (Concession), or cost recovery + profit oil (PSC). For Concession regimes: gas revenue may be ring-fenced from oil CIT or pooled depending on jurisdiction &mdash; UK UKCS: separate ring-fence means gas losses cannot shelter oil profits; Nigeria: currently pooled but may be ring-fenced under PIA implementation. Gas royalty rates in Concession regimes are typically lower than oil (US GoM: 12.5% gas vs. 12.5&ndash;18.75% oil; Norway: no royalty on gas; Algeria: 12.5&ndash;20% oil and gas). IC adjustment: sales route adds positive NPV but requires gas price assumption &mdash; model at $4/MMBtu for domestic pipeline and $7&ndash;10/MMBtu for LNG export to determine route breakeven threshold.</p>
            <p><strong>IC workflow:</strong> Step 1 &mdash; check ORCA Country Profile Reform History for anti-flaring regulation dates (regulatory tightening signal). Step 2 &mdash; estimate associated gas rate from field analogue GOR (gas-oil ratio): 200&ndash;800 scf/bbl for typical Concession fields. Step 3 &mdash; apply route adjustment to base IRR. Step 4 &mdash; IC memo: &ldquo;Associated gas at [GOR] scf/bbl, [X] MMscf/d. Route: [flare/reinject/sell]. IRR adjustment: [&plusmn;Y pp]. Anti-flaring penalty risk: [yes/no &mdash; jurisdiction and rate cited].&rdquo;</p>
            <p><em>Source: ORCA Petroleum Fiscal Intelligence Platform v356 (Aug 2026), yoburgqs.github.io/petroleum-fiscal-db/. Cross-references: FAQ A462 (associated gas in PSC fiscal treatment), FAQ A451 (associated gas Concession fiscal &mdash; original overview), FAQ A467 (gas reinjection fiscal treatment Concession/PSC/Gross Split), FAQ A439 (associated gas DMO and anti-flaring penalty in PSC).</em></p>
          </div>
        </div>

        <div class="faq-item" id="faq-A473">
          <div class="faq-q">A473. How does the Petoro/SDFI model (Norway) differ from free-carry and back-in NOC participation structures, and what IC adjustment should be applied to ORCA&rsquo;s Norway government take figure to account for Petoro&rsquo;s paying co-venturer status?</div>
          <div class="faq-a">
            <p>State equity participation in petroleum projects takes three principal forms &mdash; the paying co-venturer (Petoro/SDFI model), the free-carry NOC (exploration stage only), and the back-in right (discovery-triggered). Each has a different fiscal burden on the IOC contractor and requires a different ORCA adjustment. Understanding which model applies is essential for computing true contractor economics in state-equity-heavy regimes.</p>
            <p><strong>Petoro/SDFI model (Norway):</strong> The Norwegian State&rsquo;s Direct Financial Interest (SDFI), administered by Petoro AS, holds working interest stakes in Norwegian licenses ranging from 5% to 67.6% (Troll). Petoro pays its proportionate share of all costs &mdash; exploration, development, and operating &mdash; from the first expenditure. The SDFI pays no carry premium; IOCs are not subsidizing the state&rsquo;s interest. Petoro receives its proportionate share of production entitlement and pays Norwegian CIT/SPT at the same statutory rate as IOCs. The fiscal burden on IOC contractors from Petoro participation is zero &mdash; the state pays its own way. IC adjustment to ORCA Norway take figure: no adjustment required for Petoro/SDFI co-venturer status. ORCA&rsquo;s 65&ndash;67% take at $75/bbl already reflects the statutory Norwegian fiscal terms that apply equally to IOC and SDFI shares.</p>
            <p><strong>Free-carry NOC (Sub-Saharan Africa model):</strong> In free-carry regimes, the NOC holds a working interest stake but the IOC funds the NOC&rsquo;s exploration costs (and sometimes appraisal costs) without reimbursement. Angola&rsquo;s Sonangol historical model: NOC carried through exploration at zero cost. Ghana&rsquo;s GNPC: typically 10&ndash;15% working interest carried through exploration; the carried costs are recoverable from GNPC&rsquo;s production share post-discovery. IC adjustment: the carry burden is a cost item not captured in ORCA&rsquo;s take%. For a 20% GNPC carry at $200M exploration cost: carry burden = 20% &times; $200M = $40M. Divide by estimated project NPV to compute percentage burden &mdash; typically 0.4&ndash;1.2pp effective take equivalent.</p>
            <p><strong>Back-in right (discovery-triggered):</strong> Back-in rights give the NOC the option to acquire a working interest stake at FID (first commercial development) at historical cost &mdash; the contractor funds exploration and appraisal; the NOC pays historical cost at the development stage. Mozambique ENH: 15% FCD (first commercial development) back-in at historical cost. The back-in is effectively a discount on the NOC&rsquo;s entry &mdash; the contractor funded exploration risk without the NOC; the NOC acquires interest at below-market price at FID. IC adjustment: the back-in premium (difference between historical cost and NPV at FID) = contractor IRR give-up. Rule of thumb: 15% back-in at discovery with 3&times; exploration write-up = 0.5&ndash;1.0pp IRR give-up for IOC.</p>
            <p><strong>Comparative adjustment table:</strong> Norway SDFI/Petoro: 0pp adjustment to ORCA take. Ghana GNPC 15% free-carry: +0.4&ndash;0.8pp. Mozambique ENH 15% back-in: +0.3&ndash;0.6pp. Nigeria NNPCL (historically unreliable cash-call performance): +0.8&ndash;1.5pp effective burden. Kazakhstan KMG 15% back-in (Kazakh model): +0.5&ndash;0.9pp.</p>
            <p><em>Source: ORCA Petroleum Fiscal Intelligence Platform v356 (Aug 2026), yoburgqs.github.io/petroleum-fiscal-db/. Cross-references: FAQ A463 (Petoro/SDFI vs. free-carry vs. back-in &mdash; foundational overview), FAQ A437 (Petoro/SDFI comparative IC adjustment), FAQ A433 (state equity back-in IRR quantification), FAQ A452 (NOC cash-call failure risk and implicit carry burden).</em></p>
          </div>
        </div>

        <div class="faq-item" id="faq-A474">
          <div class="faq-q">A474. What is cross-border unitization, how does it create fiscal complexity in petroleum project economics, and what IC workflow should an analyst use to compute blended government take for a reservoir straddling two national jurisdictions?</div>
          <div class="faq-a">
            <p>Cross-border unitization arises when a petroleum reservoir straddles the boundary between two national jurisdictions &mdash; either two sovereign states (offshore median line or agreed maritime boundary) or two distinct fiscal regimes within a single federal state. The fiscal complexity stems from the fact that each jurisdiction levies its own fiscal terms on the production attributed to its side of the reservoir, and the allocation of production between jurisdictions (tract participation interest, or TPI) is determined by reservoir engineering &mdash; not fiscal optimization.</p>
            <p><strong>The blended take formula:</strong> Blended government take = (TPI_A &times; Take_A) + (TPI_B &times; Take_B), where TPI_A + TPI_B = 100% and Take_A, Take_B are the ORCA-computed government takes for each respective jurisdiction. Example: Norway (Take_A = 66%, TPI_A = 60%) + UK (Take_B = 55%, TPI_B = 40%) = (0.60 &times; 66%) + (0.40 &times; 55%) = 39.6% + 22.0% = 61.6% blended take. The 11pp take differential between Norway and UK creates a meaningful blended take even with moderate TPI allocation &mdash; a primary reason IOCs lobbied for UK/Norway redetermination when reservoirs straddle the median line (Statfjord East, Frigg, Murchison).</p>
            <p><strong>TPI redetermination risk:</strong> TPI allocations are determined at unitization agreement FID based on reservoir engineering models. As production proceeds, reservoir depletion data may show the initial TPI allocation was incorrect &mdash; triggering a redetermination. Redetermination moves TPI from one jurisdiction to the other, changing the blended take retroactively for all historic production. IC risk: a &plusmn;10pp TPI shift in a Norway/UK unitization = &plusmn;1.1pp blended take change (10% &times; 11pp differential). For a large field with $2B NPV, a 1pp take shift = $20M NPV impact. ORCA cannot capture TPI redetermination risk &mdash; analyst must add sensitivity range.</p>
            <p><strong>Jurisdictions where cross-border unitization is most material:</strong> (1) Norway/UK North Sea (Frigg, Statfjord East, Murchison): 11&ndash;13pp take differential; (2) Timor Sea (Australia/Timor-Leste JPDA): Australia PRRT vs. Timor-Leste PSC; (3) Persian Gulf (Bahrain/Saudi Arabia Abu Safah): GCC fiscal regimes; (4) Caspian Sea: Kazakhstan/Russia/Turkmenistan/Azerbaijan median-line disputes with different PSC terms.</p>
            <p><strong>IC workflow &mdash; cross-border unitization blended take:</strong> Step 1 &mdash; identify both jurisdictions and the applicable ORCA take for each (Country Profile at standard Deepwater profile). Step 2 &mdash; obtain TPI from unitization agreement or reservoir engineering estimate (range: initial estimate &plusmn;10&ndash;20%). Step 3 &mdash; compute blended take with TPI central estimate and &plusmn;10% TPI sensitivity. Step 4 &mdash; identify redetermination risk: check unitization agreement for redetermination triggers (typically every 5 years or post-appraisal well). Step 5 &mdash; IC memo disclosure: &ldquo;Cross-border unitization: TPI [A]%/[B]%. Blended take [X]% (central), range [X&minus;Y]% to [X+Y]% (&plusmn;10% TPI sensitivity). Redetermination scheduled [date or trigger]. ORCA single-country take: [country A] [take A]%, [country B] [take B]%.&rdquo;</p>
            <p><em>Source: ORCA Petroleum Fiscal Intelligence Platform v356 (Aug 2026), yoburgqs.github.io/petroleum-fiscal-db/. Cross-references: FAQ A464 (cross-border unitization &mdash; foundational overview), FAQ A434 (cross-border unitization TPI-weighted blended take mechanics), FAQ A125 (joint development zones and cross-border unitization &mdash; JDZ case studies), FAQ A445 (intra-country reservoir straddling TPI-weighted blended take).</em></p>
          </div>
        </div>

        <div class="faq-item" id="faq-A475">
          <div class="faq-q">A475. What are contractor uplift allowances in PRRT-type fiscal systems, how do they affect NPV and IRR relative to equivalent royalty/tax Concession regimes, and which jurisdictions offer the most material uplift benefits?</div>
          <div class="faq-a">
            <p>Contractor uplift allowances (also called augmented expenditure uplift, uplift credits, or supplemental allowances) are a fiscal mechanism in profit-resource-rent-type regimes (PRRT, SPT, RRT, APT) that augment a contractor&rsquo;s deductible expenditure base by a statutory percentage above actual cost. The effect is that a dollar of real expenditure generates more than a dollar of tax-deductible amount &mdash; a fiscal subsidy to capital-intensive exploration and deepwater development. Uplift is the primary mechanism by which PRRT-type regimes achieve high headline rates (40&ndash;78% marginal rate) while maintaining competitive contractor IRRs.</p>
            <p><strong>How uplift works (Australia PRRT):</strong> Exploration expenditure (pre-discovery) is uplifted at LTBR + 15% per annum, compounded. Development expenditure (post-discovery) is uplifted at LTBR + 5% per annum. LTBR (Long-Term Bond Rate) approximately 4&ndash;5% in recent years, making exploration uplift approximately 19&ndash;20% per year. For $300M exploration expenditure over 10 years: augmented amount = $300M &times; (1.195)^10 approximately $1.72B. Tax saving from augmented base = ($1.72B &minus; $0.30B) &times; 40% PRRT rate = $568M in additional tax shelter. This is the core reason why Australian deepwater exploration remains competitive despite a 40% PRRT rate on top of 30% CIT: the uplift effectively subsidizes exploration capital.</p>
            <p><strong>Norway SPT uplift:</strong> Norwegian SPT (resource rent tax) allows upfront refund of 78% of exploration costs (new from 2022 Storting decision) &mdash; functionally equivalent to uplift: exploration capital is recovered immediately at the full marginal SPT rate rather than only against future production. For development capex: Norway SPT provides a 17.69% &times; 4-year = 70.76% uplift rate spread over 4 years post-completion. For $1.2B development: $1.2B &times; 70.76% &times; 78% SPT rate = $662M NPV benefit from uplift mechanism alone.</p>
            <p><strong>UK RFES (Ring Fence Expenditure Supplement):</strong> UK oil taxation includes a Ring Fence Expenditure Supplement of 10% per year for up to 6 years on unrelieved exploration and appraisal expenditure. Maximum cumulative uplift = (1.10)^6 &minus; 1 = 61% total. At 40% corporation tax rate: $100M exploration cost generates $161M tax-deductible base = $25M additional tax benefit. More modest than Australian or Norwegian uplift but meaningful for frontier UK exploration.</p>
            <p><strong>IRR benefit vs. royalty/tax Concession at equivalent take:</strong> At the same headline government take%, PRRT-type regimes with generous uplift typically generate 2&ndash;5pp higher contractor IRR vs. a simple royalty/CIT Concession. Mechanism: uplift converts capital costs into larger deductible bases, shifting the timing of tax payments later (post-payout) and reducing the NPV of the government&rsquo;s tax stream &mdash; without reducing the total take% in the denominator. Rule of thumb: Norway (SPT with uplift/refund) vs. simple 65% Concession at same take = +3&ndash;4pp contractor IRR advantage due to refund timing and uplift base.</p>
            <p><em>Source: ORCA Petroleum Fiscal Intelligence Platform v356 (Aug 2026), yoburgqs.github.io/petroleum-fiscal-db/. Cross-references: FAQ A465 (PRRT-type contractor uplift &mdash; foundational overview), FAQ A422 (exploration cost ring-fence PSC vs. concession vs. PRRT uplift timing), FAQ A449 (PRRT-type ring-fence uplift interaction with project timing), FAQ A306 (RRT/APT and Price Swing intensity proxy).</em></p>
          </div>
        </div>

        <div class="faq-item" id="faq-A476">
          <div class="faq-q">A476. How does a production-rate sliding royalty schedule affect ORCA&rsquo;s computed government take and Swing metric, and what IC adjustment should an analyst apply to account for actual project production decline curves?</div>
          <div class="faq-a">
            <p>A sliding-scale (tiered) royalty adjusts the royalty rate based on instantaneous production rate &mdash; typically set at field level. As production declines over field life, the applicable royalty rate falls through successive tiers, reducing fiscal burden in the later production years. ORCA models a standardized plateau production profile (50k bbl/d for Deepwater basis) and applies the royalty rate applicable to that plateau rate for the full project life. This creates a systematic upward bias in ORCA&rsquo;s computed take for regimes with steep production-rate sliding royalties, because real fields spend progressively more time in lower-rate royalty tiers as they decline.</p>
            <p><strong>US Gulf of Mexico (deepwater) sliding royalty:</strong> Royalty rate tiers: 0&ndash;17,500 bbl/d: 12.5%; 17,500&ndash;35,000 bbl/d: 15%; &gt;35,000 bbl/d: 18.75% (simplified &mdash; actual tiers differ by lease vintage and water depth). For a deepwater field peaking at 50k bbl/d and declining at 15%/year: years 1&ndash;3 at 18.75%, years 4&ndash;6 at 15%, years 7+ at 12.5%. Life-weighted effective royalty approximately 13.8% vs. ORCA&rsquo;s plateau rate of 18.75% &mdash; a 5pp ORCA overstatement of royalty burden. Take correction: ORCA take approximately 3pp too high for US GoM deepwater projects on a plateau-rate basis.</p>
            <p><strong>Canada Alberta sliding royalty (oil sands and conventional):</strong> Alberta Royalty Framework: pre-payout (before project recovers all capital) = 1&ndash;9% sliding on production rate; post-payout = 25&ndash;40% sliding on netback price. The dual-sliding structure (rate and price) makes a simple ORCA uplift impossible &mdash; the pre-payout / post-payout transition dominates the early vs. late royalty burden far more than the rate-sliding component. IC approach: model explicitly with Scenario Builder using a custom opex/capex ratio to approximate payout timing.</p>
            <p><strong>Nigeria water-depth tiered royalty:</strong> Nigeria: shallow water (0&ndash;200m): 10%; deep water (200&ndash;500m): 7.5%; ultra-deep (500&ndash;800m): 5%; water depth &gt;800m: 0% (royalty holiday under PIA for frontier deepwater). For Nigeria ultra-deepwater projects on a standardized Deepwater profile, ORCA computes royalty at the applicable deepwater rate &mdash; check that the Country Profile uses the correct water depth tier. The 0% royalty for &gt;800m fields is material and may not be correctly captured in C-tier parameterized countries.</p>
            <p><strong>ORCA Swing understatement from sliding royalties:</strong> Swing (government take at $125/bbl minus take at $50/bbl) is computed at the plateau production rate. For sliding-royalty regimes, the Swing metric understates fiscal progressivity because at high prices, production accelerates (higher plateau rates &rarr; higher royalty tier); at low prices, production is deferred or curtailed (lower rates &rarr; lower royalty tier). The effective Swing is thus higher than ORCA&rsquo;s simplified calculation. IC rule of thumb: for US GoM and Canada, add 2&ndash;4pp to ORCA&rsquo;s Swing to account for the production-rate/price correlation effect.</p>
            <p><strong>IC adjustment workflow:</strong> Step 1 &mdash; identify whether the target regime has a production-rate sliding royalty (check Country Profile Reform History for &ldquo;sliding&rdquo; or &ldquo;tiered royalty&rdquo; keywords). Step 2 &mdash; estimate production profile from field analogue (plateau rate, decline rate). Step 3 &mdash; compute time-weighted average royalty across tiers using expected annual production. Step 4 &mdash; compare to ORCA plateau-rate royalty &mdash; if delta &gt;2pp, apply correction to ORCA NPV. Step 5 &mdash; IC memo: &ldquo;Production-rate sliding royalty detected. ORCA take [X]%. Life-weighted effective royalty [Y]% vs. ORCA plateau rate [Z]%. Adjusted take [X&minus;&Delta;]%.&rdquo;</p>
            <p><em>Source: ORCA Petroleum Fiscal Intelligence Platform v356 (Aug 2026), yoburgqs.github.io/petroleum-fiscal-db/. Cross-references: FAQ A466 (production-rate sliding royalty ORCA Swing understatement &mdash; foundational overview), FAQ A344 (US GoM fiscal terms IC workflow).</em></p>
          </div>
        </div>

        <div class="faq-item" id="faq-A477">
          <div class="faq-q">A477. What is the fiscal treatment of gas reinjection for pressure maintenance in PSC regimes, and how does it differ from Concession and Gross Split regimes in terms of royalty, cost oil, and profit oil treatment?</div>
          <div class="faq-a">
            <p>Gas reinjection for reservoir pressure maintenance is a routine upstream operation in oil-primary fields with high GOR (gas-oil ratio) or with gas cap management requirements. The fiscal treatment of reinjection differs materially across fiscal mechanic types &mdash; creating a hidden fiscal differentiation between regimes that share similar headline government take figures in ORCA&rsquo;s comparison tools.</p>
            <p><strong>PSC regimes (Production Sharing Contract):</strong> In most PSC regimes, gas volumes injected for pressure maintenance are excluded from the production allocation that determines cost oil and profit oil. Consequence: reinjection capex (compressor facilities, injection wells) is typically eligible as cost-recoverable expenditure against cost oil &mdash; reducing the government&rsquo;s profit oil through higher cost recovery. Reinjection opex is also cost-recoverable. However, the reinjected gas does not generate profit oil entitlement for the contractor, and when it is re-produced later as solution gas, it enters the cost oil/profit oil split at that time. Indonesia PSC example: reinjection capex and opex are included in cost recovery pool; reinjected volumes are not counted as gross production for royalty or profit oil purposes until re-produced.</p>
            <p><strong>Concession regimes:</strong> In Concession regimes, reinjected gas volumes are typically excluded from royalty computation because no commercial production has occurred. CIT treatment: reinjection capex is deductible against CIT income (depreciated over the project&rsquo;s fiscal life). Reinjection opex is deductible in the year incurred. When reinjected gas is re-produced as solution gas in oil production, it is counted in the gross production stream and subject to royalty at that point. UK UKCS: reinjection capex eligible for Ring Fence Capital Allowances (100% first-year in some cases). Norway: reinjection capex eligible for 24% uplift over 6 years plus full CIT deduction at 22%; SPT deduction in same year.</p>
            <p><strong>Indonesia Gross Split PSC:</strong> Gross Split does not have a cost recovery mechanism &mdash; all costs are the contractor&rsquo;s burden, with no reimbursement through cost oil. However, the Gross Split regulation includes EOR (enhanced oil recovery) components in the variable split calculation. Gas reinjection for EOR purposes (CO2 injection, water injection, gas injection to maintain pressure) may trigger an additional variable split component of +2&ndash;5pp contractor share on remaining production. This is the Gross Split analog to cost recovery eligibility &mdash; the EOR uplift partially compensates the contractor for reinjection costs without a cost oil mechanism.</p>
            <p><strong>IC materiality threshold:</strong> Gas reinjection becomes fiscally material (affects take by &gt;1pp) when: reinjection capex exceeds $100M; reinjection rate exceeds 50% of produced gas volumes; or the field life is long enough that re-production of reinjected gas represents material production. For typical deepwater fields with 10&ndash;15% GOR (low associated gas), reinjection is a minor fiscal item. For high-GOR gas cap fields (GOR &gt;2,000 scf/bbl), reinjection fiscal treatment can affect NPV by $50&ndash;200M.</p>
            <p><em>Source: ORCA Petroleum Fiscal Intelligence Platform v356 (Aug 2026), yoburgqs.github.io/petroleum-fiscal-db/. Cross-references: FAQ A467 (gas reinjection &mdash; foundational overview Concession/PSC/Gross Split), FAQ A447 (gas reinjection EOR fiscal treatment PSC vs. Concession), FAQ A462 (associated gas PSC fiscal pathways including reinjection), FAQ A471 (gas monetization route selection and reinjection fiscal treatment).</em></p>
          </div>
        </div>

        <div class="faq-item" id="faq-A478">
          <div class="faq-q">A478. How should an IC analyst calibrate the ORCA Stability Score to a project-specific discount rate premium, and how does investment horizon (10-year vs. 25-year development) change the magnitude of the premium?</div>
          <div class="faq-a">
            <p>The ORCA Stability Score is a composite index (0&ndash;100) reflecting the probability of material adverse fiscal reform for a country&rsquo;s petroleum regime. The score aggregates four inputs: Reform History frequency (number and magnitude of pro-government reform events per decade), political risk indicators (PRS/ICRG composite), Price Swing (proxy for fiscal progressivity under stress), and structural stabilization clause presence. A score of 100 represents a regime with zero observed reform events, binding stabilization clauses, and OECD-equivalent rule of law. A score of 0 represents a regime with active expropriation history or no rule of law.</p>
            <p><strong>Discount rate calibration by score tier:</strong> The Stability Score should be used to add a country-specific risk premium to the project base WACC. Tier thresholds and recommended premiums: Score &gt;70 (Stable/OECD-equivalent: Norway, UAE, Qatar, Australia): 0&ndash;1pp premium. Score 50&ndash;70 (Moderate: Angola, Peru, Oman, Trinidad): 1&ndash;2pp premium. Score 30&ndash;50 (Elevated: Nigeria, Iraq, Algeria, Indonesia): 2&ndash;4pp premium. Score &lt;30 (High Risk: Venezuela, Bolivia, Libya, Sudan): 4&ndash;6pp premium. These are guidelines &mdash; analyst judgment must apply context (e.g., a country with Score 45 and active fiscal reform legislation warrants the top of the range; a country with Score 45 but a 20-year-old unchanged regime warrants the bottom).</p>
            <p><strong>Investment horizon scaling:</strong> The probability of a material fiscal reform increases non-linearly with project duration. A regime that reformed once in 20 years has an annual frequency of 5%. Over a 10-year project, P(at least one reform) = 1 &minus; (0.95)^10 = 40%. Over a 25-year project: P = 1 &minus; (0.95)^25 = 72%. The discount rate premium should scale with the expected P(reform) over the project life. Rule of thumb: for a 25-year project in a Score-45 regime, apply the top of the premium range (4pp). For a 10-year FPSO project in the same regime, apply the midpoint (3pp) &mdash; the shorter window reduces expected P(reform) by approximately one-third.</p>
            <p><strong>Combining Stability Score premium with ORCA base take:</strong> IC workflow: Step 1 &mdash; obtain ORCA base take% at $75/bbl (Deepwater profile). Step 2 &mdash; note ORCA Stability Score from Country Profile. Step 3 &mdash; determine project life (10/20/25 years). Step 4 &mdash; apply discount rate premium: base WACC (10%) + Stability Score premium (0&ndash;6pp) = project WACC. Step 5 &mdash; recompute NPV with adjusted WACC and compare to ORCA standard-WACC result. Step 6 &mdash; IC memo: &ldquo;Stability Score [S]. Base WACC 10%. Country-specific premium [X]pp (Score [S], [N]-year project horizon). Project WACC [10+X]%. NPV at adjusted WACC $[Y]M vs. ORCA standard $[Z]M.&rdquo;</p>
            <p><strong>Interaction with stabilization clauses:</strong> If the target contract includes a strong stabilization clause (economic equilibrium or freeze clause &mdash; see FAQ A458), the effective Stability Score premium should be reduced by 1&ndash;2pp (economic equilibrium) or 2&ndash;3pp (legislative freeze). Mozambique Area 4 PSC includes an economic equilibrium stabilization clause &mdash; warranting a 1pp premium reduction from the country-level Stability Score estimate.</p>
            <p><em>Source: ORCA Petroleum Fiscal Intelligence Platform v356 (Aug 2026), yoburgqs.github.io/petroleum-fiscal-db/. Cross-references: FAQ A468 (Stability Score and discount rate calibration &mdash; foundational overview), FAQ A458 (stabilization clause strength and IC discount rate calibration), FAQ A420 (renegotiation risk assessment probability-weighted NPV haircut), FAQ A470 (fiscal regime transition probability and vintage analysis).</em></p>
          </div>
        </div>

        <div class="faq-item" id="faq-A479">
          <div class="faq-q">A479. How should an IC analyst model a fully integrated LNG project where upstream gas production, pipeline transport, and liquefaction are held by the same IOC, and what does ORCA capture vs. what must be added from external sources?</div>
          <div class="faq-a">
            <p>A fully integrated LNG project &mdash; where the IOC holds equity in the upstream gas field, the pipeline/feeder system, and the liquefaction plant &mdash; involves three distinct fiscal layers, each with its own tax jurisdiction, ring-fence rule, and potential government participation. ORCA captures only the upstream layer. The IC analyst must construct the remaining two layers from external sources and combine them into an integrated effective take figure for full-project IC analysis.</p>
            <p><strong>Layer 1 &mdash; Upstream gas production (ORCA captures this):</strong> Royalty on gas production (wellhead royalty, where applicable). Profit gas in PSC regimes. CIT on upstream income. PRRT/SPT where applicable (Australia, Norway). ORCA&rsquo;s government take for the upstream layer is the starting point. For a PSC regime, this is the sum of royalty + NOC profit gas share + CIT on contractor&rsquo;s profit gas, expressed as a % of FOB LNG value. Rule of thumb: upstream layer accounts for 55&ndash;70% of integrated LNG take for typical Sub-Saharan Africa/SE Asia PSC regimes.</p>
            <p><strong>Layer 2 &mdash; Midstream pipeline (typically not ring-fenced separately):</strong> In most integrated LNG structures, the feeder pipeline from field to LNG plant is treated as part of either the upstream or the LNG plant cost base &mdash; there is rarely a separate pipeline ring-fence at the tax level. Key question: is the pipeline owned by the upstream entity or a separate pipeline company? If separate, a transfer pricing issue arises: the price at which gas transfers from upstream to pipeline determines upstream profit gas and downstream CIT base. For IOC-owned integrated structures, the pipeline is typically included in the LNG plant capital base and depreciated under the LNG company CIT framework.</p>
            <p><strong>Layer 3 &mdash; LNG plant / liquefaction (ORCA does NOT capture this):</strong> The LNG plant is typically a separate legal entity from the upstream PSC contractor. Fiscal items: LNG company CIT (at standard corporate rate &mdash; often higher than the upstream PSC contractor rate if special upstream incentives apply). LNG export levy (where imposed). LNG plant WHT on dividends to non-resident IOC shareholders. Average LNG plant fiscal layer for Sub-Saharan Africa: 10&ndash;20pp additional effective take vs. upstream-only ORCA figure.</p>
            <p><strong>Integrated IC workflow:</strong> Step 1 &mdash; use ORCA Country Profile upstream take (e.g., Mozambique: 58&ndash;65% at Deepwater $75/bbl proxy). Step 2 &mdash; add LNG midstream layer: estimate plant CIT; compute liquefaction margin as FOB LNG price &minus; plant gate price &minus; LNG opex &minus; tolling fee. Step 3 &mdash; add WHT layer: dividend WHT rate &times; IOC equity % &times; post-tax liquefaction income. Step 4 &mdash; compute integrated take = (upstream government revenues + liquefaction CIT + WHT) / (FOB LNG revenue from all volumes). Step 5 &mdash; IC memo: &ldquo;Upstream take (ORCA): [X]%. Liquefaction layer CIT: [Y]pp. WHT layer: [Z]pp. Integrated effective take: [X+Y+Z]%. Note: ORCA upstream-only basis; midstream layer modeled from [source].&rdquo;</p>
            <p><strong>Key caveat &mdash; upstream/midstream fiscal boundary:</strong> The gas transfer price from upstream to LNG plant is the most consequential assumption. If the government sets the transfer price at cost-plus (regulated), the upstream contractor earns minimal profit on gas &mdash; reducing upstream CIT but shifting income to the LNG entity. In self-dealing integrated structures, transfer pricing rules (BEPS Action 8&ndash;10 arm&rsquo;s length principle) apply and may be enforced by the host government to maximize their tax take.</p>
            <p><em>Source: ORCA Petroleum Fiscal Intelligence Platform v356 (Aug 2026), yoburgqs.github.io/petroleum-fiscal-db/. Cross-references: FAQ A469 (integrated LNG fiscal modeling &mdash; foundational overview), FAQ A436 (LNG fiscal boundary upstream vs. liquefaction cost oil recovery), FAQ A440 (East Africa deepwater LNG all-in IC workflow), FAQ A428 (transfer pricing in upstream PSC and BEPS Action 8&ndash;10).</em></p>
          </div>
        </div>

        <div class="faq-item" id="faq-A480">
          <div class="faq-q">A480. What is fiscal regime transition probability and how can an IC analyst use ORCA&rsquo;s Reform History frequency data, Price Swing, and Vintage Analysis to build a quantified probability-weighted NPV for a long-duration petroleum investment?</div>
          <div class="faq-a">
            <p>Fiscal regime transition probability is the estimated likelihood that a petroleum contract will face materially adverse fiscal change during a project&rsquo;s production life &mdash; through legislation (tax rate increase, new levy, royalty rate change), renegotiation (government-compelled contract modification), or administrative action (retroactive cost disallowance, export levy). Over a 20&ndash;30 year production horizon, fiscal regime transition is the largest single source of underperformance vs. FID-modeled contractor returns. Quantifying this probability is therefore a core IC competency &mdash; and ORCA provides three data inputs to support the calculation.</p>
            <p><strong>ORCA inputs for transition probability:</strong> (1) Reform History: number and direction of dated reform events per country &mdash; the historical frequency of pro-government fiscal reforms. (2) Price Swing: the difference in government take% between $125/bbl and $50/bbl &mdash; a high-Swing progressive regime is less likely to face windfall reform at high prices (progressive terms already extract higher share); a low-Swing flat-take regime is more vulnerable to discretionary windfall reform. (3) Vintage Analysis: the 10-year rolling average take by fiscal mechanic &mdash; countries where the vintage trend shows consistently rising government take (structural drift upward) are more likely to continue drifting. Countries with declining or flat vintage trends (mature OECD, stable Gulf states) are less likely to reform.</p>
            <p><strong>Annual reform frequency computation:</strong> For each target country: count pro-government reform events in ORCA Reform History over the past 20 years (N_reform). Annual frequency = N_reform / 20. P(at least one reform in T years) = 1 &minus; (1 &minus; N_reform/20)^T. Example: Nigeria &mdash; approximately 6 pro-government reform events in 20 years = frequency 0.30/year. P(reform in 10 years) = 1 &minus; (0.70)^10 = 97%. Nigeria is effectively a near-certain reform jurisdiction for any long-duration project &mdash; the IC analysis must include a reform scenario, not treat it as optional sensitivity.</p>
            <p><strong>Magnitude calibration:</strong> Low-magnitude reform (1&ndash;3pp take increase): royalty rate adjustment, minor levy addition &mdash; affects NPV by 5&ndash;10%. Medium-magnitude (4&ndash;7pp): profit oil split revision, new SPT/windfall levy &mdash; affects NPV by 15&ndash;25%. High-magnitude (8&ndash;15pp): full fiscal regime replacement, cost recovery ceiling reduction &mdash; affects NPV by 25&ndash;40%. Rule of thumb: use median historical reform magnitude as the central estimate and the 75th percentile as the stress scenario.</p>
            <p><strong>Probability-weighted NPV framework:</strong> Step 1 &mdash; compute base NPV (no reform, ORCA take unchanged). Step 2 &mdash; compute stress NPV (reform occurs at year 8&ndash;12, adding median historical reform magnitude to effective take). Step 3 &mdash; apply probability weights: P(no reform) &times; base NPV + P(reform) &times; stress NPV = probability-weighted NPV. Step 4 &mdash; sensitivity: vary reform timing (early = more damaging, late = less damaging) and magnitude. Step 5 &mdash; IC memo: &ldquo;Reform History frequency [N] events / 20 years. Annual frequency [f]. P(reform in [T]-year project) = [P]%. Central reform scenario: +[&Delta;]pp take at year [Y]. Probability-weighted NPV = $[X]M ([P_base]% &times; $[base]M + [P_reform]% &times; $[stress]M). ORCA base take [take_base]%, post-reform estimated [take_reform]%.&rdquo;</p>
            <p><strong>Integration with Vintage Analysis:</strong> Vintage Analysis provides the structural drift context. If the Vintage Analysis tab shows a regime&rsquo;s average take has risen 10pp over the past 30 years, a simple linear extrapolation suggests an additional 3&ndash;4pp take rise over the next 10 years &mdash; even in the absence of a discrete reform event. IC rule of thumb: add 0.3pp per year of Vintage drift as a &ldquo;structural drift&rdquo; adjustment to discount rate, separate from the discrete reform probability premium.</p>
            <p><em>Source: ORCA Petroleum Fiscal Intelligence Platform v356 (Aug 2026), yoburgqs.github.io/petroleum-fiscal-db/. Cross-references: FAQ A470 (fiscal regime transition probability &mdash; foundational overview), FAQ A383 (Vintage Analysis IC workflow &mdash; decade-trend context), FAQ A341 (fiscal regime price cycle vulnerability and reform trigger analysis), FAQ A420 (renegotiation risk assessment probability-weighted NPV haircut), FAQ A478 (Stability Score and discount rate calibration by investment horizon).</em></p>
          </div>
        </div>

'''

# Insert after FAQ A470 closing tag (before the "Back to top" anchor)
a470_end = '        </div>\n\n      <a href="#tab-btn-tmeth"'
assert a470_end in content, "A470 end marker not found!"
content = content.replace(a470_end, faq_new + '      <a href="#tab-btn-tmeth"', 1)
print(f"FAQs A471-A480 inserted. New length: {len(content)}")

# ── VERSION SWEEP v355 → v356 ──
content = content.replace('v355', 'v356')
print(f"v355 -> v356 replacements done. Count was 30.")

# ── FAQ COUNT 470 → 480 ──
content = content.replace('>470<', '>480<')
content = content.replace('A1&ndash;A470', 'A1&ndash;A480')
content = content.replace('470 analyst FAQs', '480 analyst FAQs')
content = content.replace('470 Analyst FAQs', '480 Analyst FAQs')
content = content.replace('470 FAQs', '480 FAQs')
print("FAQ count 470 -> 480 done")

# Verify counts
print(f"v356 occurrences: {content.count('v356')}")
print(f">480< occurrences: {content.count('>480<')}")
print(f"faq-A480: {'faq-A480' in content}")
print(f"faq-A471: {'faq-A471' in content}")

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(content)
print("File saved successfully.")
