#!/usr/bin/env python3
"""Insert FAQs A281-A290 into index.html for Cycle 242."""
import sys

HTML = 'C:/Users/ztuch/petroleum-fiscal-db/index.html'

with open(HTML, encoding='utf-8') as f:
    content = f.read()

new_faqs = """
    <details class="faq-item" id="faq-A281" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A281.</span><strong>A281.</strong> How does fiscal regime type affect exploration dry-hole cost recovery, and what is the IC adjustment methodology?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);">
        <p>Dry-hole cost recovery varies dramatically by fiscal mechanic and ring-fence structure. An exploration-stage IC memo that ignores dry-hole treatment will systematically overstate IRR for PSC regimes relative to concessions with company-level CIT ring-fences.</p>
        <p><strong style="color:var(--text);">By fiscal mechanic:</strong> (1) Concession with company-level CIT ring-fence (Norway, UK, Australia): dry-hole costs are deductible against all company income at the CIT rate (Norway 78% uplift, UK RFCT 40%, Australia 30%). A $100M dry-hole costs the IOC $22M after-tax in Norway vs. $70M in a strict license-level ring-fence jurisdiction. (2) PSC with license-level cost recovery: dry-hole costs are typically not recoverable &mdash; a 100% contractor burden. ORCA per-contract take does not capture this risk. (3) PRRT (Australia): exploration expenditure receives a 150% uplift transferable across the portfolio &mdash; dry-hole is effectively a 150% deductible cost.</p>
        <p><strong style="color:var(--text);">IC adjustment framework:</strong> (1) Identify ring-fence type using ORCA Country Profile. (2) Estimate exploration well count and dry-hole probability. (3) Compute expected dry-hole cost burden: [wells &times; P(dry) &times; well cost &times; (1 &minus; effective recovery rate)]. Norway recovery rate ~78%; license-level PSC: 0%. (4) Subtract from ORCA-benchmark IRR: a $150M expected dry-hole burden over 5 years reduces IRR approximately 0.8&ndash;1.5pp on a standard Deepwater profile.</p>
        <p><strong style="color:var(--text);">Rule of thumb:</strong> Company-level CIT concession (Norway/UK/Australia): ICR impact &lt;1pp. License-level ring-fence (Nigeria PSC, Angola PSC): adjust IRR down 1&ndash;3pp for high-risk exploration plays. PRRT (Australia): exploration uplift makes dry-hole least burdensome of the three.</p>
        <p><strong style="color:var(--text);">Source:</strong> ORCA v309 (Aug 2026). HMRC RFCT Exploration Expenditure Relief (OT45100); Norwegian Petroleum Tax Act &sect;3f; Deloitte International Petroleum Fiscal Guide 2024. Cross-references: FAQ A69 (fiscal ring-fencing); FAQ A163 (cross-block cost consolidation); FAQ A213 (breakeven vs. field-specific breakeven).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A282" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A282.</span><strong>A282.</strong> What is the fiscal treatment of cost overruns in PSCs, and how should an IC analyst model them?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);">
        <p>PSC cost recovery ceilings create a scenario where cost overruns beyond the ceiling are absorbed entirely by the contractor &mdash; unlike concessions where the government shares in overruns through reduced CIT revenue.</p>
        <p><strong style="color:var(--text);">PSC mechanics under overrun:</strong> If base-case costs consume 40% of production but a 50% overrun pushes costs to 60%, the ceiling (say, 50%) becomes binding. Uncovered costs roll forward as a carryforward. Nigeria model PSC: 80% ceiling; Angola Deepwater: typically 65%; Indonesia PSC: 40&ndash;60% depending on vintage. In low-price environments, carryforward may never clear before license expiry.</p>
        <p><strong style="color:var(--text);">Concession treatment:</strong> Cost overruns are fully deductible subject to CIT timing and ring-fence. Every $100M overrun reduces IRR approximately 0.4&ndash;0.8pp. IRR degradation is linear vs. the non-linear PSC case when ceiling becomes binding.</p>
        <p><strong style="color:var(--text);">4-step IC overrun sensitivity workflow:</strong> (1) Identify the PSC cost recovery ceiling in ORCA Country Profile. (2) Run Scenario Builder at base-case capex, then +25% and +50% overrun. (3) Check whether the ceiling becomes binding at each scenario. (4) IC memo: present a cost overrun tail risk table; flag if ceiling binds at +25% overrun &mdash; cost discipline becomes a fiscal risk management tool.</p>
        <p><strong style="color:var(--text);">Source:</strong> ORCA v309 (Aug 2026). Johnston, D. (2003) Ch. 6 (cost recovery mechanics and ceiling interactions); Wood Mackenzie PSC Cost Recovery Risk Study 2024; Angola ANPG Model PSC Accounting Procedure. Cross-references: FAQ A42 (PSC cost recovery cap); FAQ A111 (cost recovery carryforward); FAQ A218 (PSC cost recovery cap price sensitivity); FAQ A277 (PSC cost recovery timing and production decline).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A283" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A283.</span><strong>A283.</strong> How should an analyst interpret and use the ORCA Stability Score in an IC memo, and what does it not capture?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);">
        <p>The ORCA Stability Score (0&ndash;5 dots) measures fiscal reform frequency since 2010 &mdash; documented fiscal change events in the reform history database. It does NOT measure geopolitical stability, contract sanctity, or the direction of reform.</p>
        <p><strong style="color:var(--text);">What the score does NOT capture:</strong> (1) Direction of reform &mdash; royalty reductions and increases count equally. (2) Severity &mdash; a technical correction and a full regime overhaul both count as 1 event. (3) Contract stabilization &mdash; a weak statutory score may coexist with strong contractual stabilization clauses (FAQ A73). (4) Political risk &mdash; use Damodaran CRP (FAQ A162) alongside Stability Score. (5) Forward-looking risk &mdash; the score is backward-looking since 2010 only.</p>
        <p><strong style="color:var(--text);">3-step IC memo integration:</strong> (1) Cite as a data point: "ORCA Stability Score [X/5] &mdash; [X events since 2010]. Direction of reform: [favorable/unfavorable/mixed] per Reform History tab." (2) For Score 0&ndash;2: apply a +5pp take sensitivity in Scenario Builder and present NPV impact as a fiscal reform haircut. (3) For Score 4&ndash;5: note low reform frequency but distinguish from contractual protection &mdash; Norway (Score 5) retains retroactive legislation authority despite behavioral stability.</p>
        <p><strong style="color:var(--text);">Source:</strong> ORCA v309 (Aug 2026). ORCA Reform History database (2010&ndash;2026 fiscal events); Damodaran (2026) Country Risk; ICRG Political Risk Ratings (2025); Johnston (2003) Ch. 15. Cross-references: FAQ A73 (stabilization clauses vs. Stability Score); FAQ A76 (recently-reformed regime IC workflow); FAQ A216 (fiscal stability risk quantification).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A284" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A284.</span><strong>A284.</strong> How do production-linked milestone payments (production bonuses) affect IRR, and how does ORCA handle them?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);">
        <p>Production bonuses (PBs) are triggered when cumulative production or daily rate crosses defined thresholds. Unlike signature bonuses (paid Day 0), PBs are contingent on production success &mdash; a $50M PB at 50 MMbbl cumulative has zero NPV impact if the project produces only 40 MMbbl.</p>
        <p><strong style="color:var(--text);">Fiscal treatment by regime:</strong> PSC jurisdictions (Nigeria, Angola, Indonesia): PBs are typically cost-recoverable at the cost oil pool. Concession jurisdictions: PBs are deductible against CIT (50% sharing in Norway, 30% in Australia). Iraq TSC: PBs are structured as a $/bbl fee reduction on remuneration above the production threshold.</p>
        <p><strong style="color:var(--text);">ORCA Scenario Builder handling:</strong> ORCA does not model production-milestone PBs natively. Best practice: (1) Estimate PB trigger date from ORCA production profile. (2) Enter discounted PB as additional capex (discounted to Year 0 at WACC). (3) Present as a sensitivity: "Base case IRR [X]% excludes a $[Y]M PB at 50 MMbbl cumulative. If triggered, IRR adjusts to [Z]%." (4) IC memo: flag tax treatment and probability of trigger.</p>
        <p><strong style="color:var(--text);">Rule of thumb:</strong> PBs &lt;3% of gross project NPV: footnote only. 3&ndash;10%: model explicitly. &gt;10%: report both triggered and un-triggered IRR in the base case table as primary IC metrics.</p>
        <p><strong style="color:var(--text);">Source:</strong> ORCA v309 (Aug 2026). Johnston, D. (2003) Ch. 4 (bonus structures); IHS Markit Upstream Fiscal Database 2024; Nigeria NUPRC Model PSC 2023 Articles 13&ndash;15. Cross-references: FAQ A266 (signature bonus and MWP DCF); FAQ A279 (fiscal front-loading risk); FAQ A57 (government take exclusions).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A285" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A285.</span><strong>A285.</strong> What fiscal considerations apply to gas cap reinjection vs. monetization decisions, and how does ORCA model the difference?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);">
        <p>Gas cap reinjection vs. monetization is a reservoir management decision with a large fiscal dimension. Flaring penalties, reinjection obligations, DMO pricing, and gas-specific royalties create a fiscal asymmetry that can reverse the economics of monetization relative to pure reinjection.</p>
        <p><strong style="color:var(--text);">Fiscal treatment by decision:</strong> (1) Reinjection: gas is not produced commercially &mdash; no royalty, no profit sharing. In PSCs, reinjection costs are typically cost-recoverable; in concessions, CIT-deductible. Reinjection is effectively government-subsidized through cost recovery. (2) Gas monetization: subject to royalty (Nigeria 10% gas vs. 20% oil), profit sharing, and DMO obligation (Indonesia: DMO gas at regulated price below market). (3) Flaring penalties: $2&ndash;15/Mcf equivalent &mdash; typically non-deductible, acting as a tax on the reinjection alternative foregone.</p>
        <p><strong style="color:var(--text);">ORCA modeling approach:</strong> Run Scenario Builder at the gas-equivalent netback price (e.g., $5/MMBtu Henry Hub &asymp; $29/bbl oil equivalent). Compare NPV/IRR of gas monetization vs. a reinjection-only scenario (run at $0 gas revenue + reinjection capex as additional input). In DMO jurisdictions, use the blended price (DMO barrels at regulated price + export barrels at market). IC memo: "Fiscal breakeven for gas monetization: gas netback above $[Y]/bbl oil-equivalent (ORCA Scenario Builder)."</p>
        <p><strong style="color:var(--text);">Source:</strong> ORCA v309 (Aug 2026). Indonesia SKK Migas PTK 036; Nigeria NUPRC 2023 gas flaring regulations; Wood Mackenzie Associated Gas Monetization Economics 2024; EY Global Oil and Gas Tax Guide 2024. Cross-references: FAQ A60 (gas vs. oil fiscal adjustments); FAQ A84 (gas-weighted country adjustment); FAQ A239 (gas-condensate and NGL fiscal differentiation).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A286" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A286.</span><strong>A286.</strong> How do area fees, rental fees, and surface use charges interact with ORCA government take?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);">
        <p>Area fees, rental fees, and surface use charges are per-area or per-period charges imposed on license holders regardless of production. ORCA statutory take calculation excludes these fees &mdash; they are para-fiscal costs requiring block-specific adjustment, and their materiality is often underestimated in early-stage IC memos.</p>
        <p><strong style="color:var(--text);">Types and magnitudes:</strong> (1) Exploration period rentals: $0.50&ndash;$5.00/km&sup2;/year. For a 5,000 km&sup2; block at $2/km&sup2;/year over 5 years: $50M total &mdash; material for marginal fields. (2) Development/production rentals: US GoM $0&ndash;$3/acre/year; UK NSTA licence fee varies by block size. (3) Surface use payments (onshore): US $5&ndash;$25/acre/year; Nigeria community levy approximately 3% of OPEX. (4) Environmental license fees: Australia NOPSEMA regulatory levy $0.5&ndash;$2M/year.</p>
        <p><strong style="color:var(--text);">IC adjustment methodology:</strong> (1) Identify fee structure from ORCA Country Profile or bid round documentation. (2) Compute total PV of area fees: [annual fee &times; area &times; years &times; discount factor]. (3) Express as take-equivalent: [PV fees / Gross NPV at $75]. Area fees add 0.3&ndash;2pp to effective take for large deepwater blocks, 1&ndash;5pp for small onshore blocks. (4) IC memo: "ORCA statutory take [X]% excludes area rentals of $[Y]M (PV) &asymp; [Z]pp effective take uplift. All-in effective take: [X+Z]%."</p>
        <p><strong style="color:var(--text);">Source:</strong> ORCA v309 (Aug 2026). BOEM OCS Lease Rental Rates (2024, 30 CFR 218); NSTA UKCS Licence Fees Schedule 2024; Nigeria NUPRC surface fee regulations 2023; Johnston, D. (2003) Ch. 2. Cross-references: FAQ A57 (government take exclusions); FAQ A254 (local content obligations); FAQ A265 (insurance and bonding obligations).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A287" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A287.</span><strong>A287.</strong> What is a profit petroleum tier schedule, and how does tiered profit oil affect take across price environments?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);">
        <p>A profit petroleum tier schedule defines how production (after cost oil recovery) is split between government and contractor at different production rate or R-factor levels. It is the primary mechanism through which PSC governments capture windfall gains in high-production or high-price environments.</p>
        <p><strong style="color:var(--text);">Common trigger structures:</strong> (1) Production-rate triggers: Angola Block 32 contractor share falls from 40% to 15% across 3 production tiers. (2) R-factor triggers: cumulative revenue/cost ratio thresholds (FAQ A70). Higher prices push R-factor up faster, triggering higher-take tiers earlier. (3) Hybrid: Guyana Stabroek uses production + R-factor triggers simultaneously, compounding the government&rsquo;s upside capture.</p>
        <p><strong style="color:var(--text);">IC price sensitivity impact:</strong> A tiered schedule creates a convex take curve. For an R-factor PSC at $50/bbl, the project may be in Tier 1 (40% contractor share); at $100/bbl, in Tier 3 (20% contractor share). ORCA&rsquo;s Price Swing metric captures this convexity &mdash; R-factor PSC countries show high Swing values (18&ndash;28pp) vs. concession countries (5&ndash;12pp).</p>
        <p><strong style="color:var(--text);">4-step IC workflow:</strong> (1) Run Fiscal Compare &mdash; identify countries with Swing &gt;18pp. (2) Load Country Profile &mdash; review profit oil tier schedule. (3) Run Scenario Builder at $50/$75/$100 &mdash; observe IRR inflection points near tier boundaries. (4) IC memo: "Profit oil split is tiered &mdash; at $75/bbl Deepwater, contractor is in Tier [N] ([X]% share). At $100/bbl, enters Tier [N+1] ([Y]% share). ORCA Price Swing: [Z]pp."</p>
        <p><strong style="color:var(--text);">Source:</strong> ORCA v309 (Aug 2026). Angola Block 32 PSC (ANPG 2004); Guyana Stabroek Block PSC 2016 (ExxonMobil, Hess, CNOOC); Johnston, D. (2003) Ch. 6; Wood Mackenzie Deepwater West Africa Fiscal Database 2024. Cross-references: FAQ A70 (R-factor mechanics); FAQ A184 (price sensitivity tiers by fiscal mechanic); FAQ A205 (Price Swing portfolio construction).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A288" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A288.</span><strong>A288.</strong> How does ORCA handle countries with multiple concurrent fiscal regimes within a single legal system?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);">
        <p>ORCA models each country using its dominant fiscal mechanic. For multi-regime jurisdictions, the Country Profile displays the primary regime with a multi-mechanic banner indicating alternative regimes. The Fiscal Compare output reflects dominant-mechanic take.</p>
        <p><strong style="color:var(--text);">Key multi-regime countries:</strong> (1) USA: ORCA models Federal OCS (BOEM) concession as primary (royalty 12.5&ndash;18.75% + CIT 21%). Alaska&rsquo;s PPT adds 15&ndash;20pp effective take above the federal benchmark &mdash; IC memos for US onshore must specify state regime. (2) Brazil: pre-salt (partilha de produ&ccedil;&atilde;o, operated by Petrobras) take is typically 5&ndash;15pp higher than ORCA&rsquo;s post-salt concession figure. (3) Indonesia: Gross Split PSC (2017) coexists with legacy Cost Recovery PSC contracts. Gross Split take is 5&ndash;12pp higher for the same profile. (4) Iraq: TSC (central government) and KRG PSC (Kurdistan) are legally separate regimes with separate ORCA entries.</p>
        <p><strong style="color:var(--text);">IC workflow:</strong> (1) Check Country Profile for fiscal mechanic banner. (2) Identify which sub-regime applies to your specific block. (3) Apply take adjustment in Scenario Builder if your regime differs from ORCA primary. (4) IC memo: "ORCA models Brazil as concession (post-salt basis). Target block is pre-salt under the Partilha regime. Take adjusted +[X]pp to reflect pre-salt structure, based on [source]. Base ORCA figure is not directly applicable."</p>
        <p><strong style="color:var(--text);">Source:</strong> ORCA v309 (Aug 2026). BOEM OCS Royalty Management 2024; Brazilian ANP Law 12351/2010; Indonesian Government Regulation 53/2017; Iraq MoO TSC framework; KRG Petroleum Law 2007. Cross-references: FAQ A268 (mixed-regime country IC protocol); FAQ A227 (fiscal mechanic detection algorithm); FAQ A203 (when mechanic type changes the IC recommendation).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A289" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A289.</span><strong>A289.</strong> How should an IOC analyst assess fiscal risk when a country is under sanctions, licensing moratorium, or force majeure?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);">
        <p>Licensing moratoria, sanctions, and force majeure events suspend normal fiscal regime operation. They create a risk category that ORCA&rsquo;s Stability Score does not capture &mdash; the score counts fiscal parameter changes, not operational suspension events.</p>
        <p><strong style="color:var(--text);">Three event types and IC treatment:</strong> (1) Licensing moratorium (US federal offshore, Brazil pre-salt bid round suspensions): no new acreage available; existing licenses continue under original terms. Use ORCA fiscal data normally for existing holders; flag no new access for greenfield screening. (2) International sanctions (Iran, Venezuela, Russia/Sakhalin): ORCA maintains fiscal data but these countries are non-accessible for Western IOC investment under current regulatory frameworks. IC disclosure: "[Country] fiscal data (ORCA [tier] directional proxy) is for academic benchmarking only. Investment prohibited under [US/EU/UK] sanctions as of [date]." (3) Force majeure/conflict (Libya, Yemen, South Sudan): active force majeure suspends production obligations and cost recovery timelines. IC: present ORCA data as pre-force majeure baseline; apply a timeline extension discount as a scenario sensitivity.</p>
        <p><strong style="color:var(--text);">3-step IC risk integration:</strong> (1) Run Fiscal Compare to establish fiscal baseline as if operationally normal. (2) Overlay operational status from OFAC, EU sanctions list, or IEA country risk database. (3) IC memo: present take data with explicit qualification of operational access. For force majeure, quantify timeline extension as an IRR sensitivity.</p>
        <p><strong style="color:var(--text);">Source:</strong> ORCA v309 (Aug 2026). OFAC SDN List (US Treasury, 2026); EU Council Regulation on Russia sanctions (2022 as amended); IEA World Energy Outlook 2025; Wood Mackenzie Geopolitical Risk Impact on Upstream Portfolios (2024). Cross-references: FAQ A226 (sovereign vs. fiscal risk); FAQ A162 (country-risk-adjusted WACC); FAQ A200 (resource nationalism probability scoring).</p>
      </div>
    </details>

    <details class="faq-item" id="faq-A290" style="border:1px solid var(--border);border-radius:6px;margin-bottom:8px;overflow:hidden;">
      <summary style="padding:12px 16px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text);background:var(--surface2);display:flex;align-items:center;gap:10px;list-style:none;"><span style="color:var(--accent);font-weight:800;flex-shrink:0;">A290.</span><strong>A290.</strong> What is the fiscal treatment of LNG liquefaction tolling fees vs. integrated LNG project structures for IC analysis?</summary>
      <div style="padding:14px 16px;font-size:13px;line-height:1.7;color:var(--text);">
        <p>LNG projects can be structured as integrated (upstream + liquefaction under unified fiscal treatment) or tolling (upstream contractor pays a third-party liquefaction fee, separate from upstream fiscal regime). The distinction fundamentally changes the IC analysis &mdash; tolling fees reduce contractor revenue before fiscal allocation.</p>
        <p><strong style="color:var(--text);">Tolling structure:</strong> Contractor sells gas at wellhead at a netback price &mdash; LNG export price minus shipping, tolling fee ($1.50&ndash;$3.50/MMBtu), and insurance. Government take is applied to the net wellhead value. ORCA Scenario Builder: enter the blended netback price as the $/bbl oil-equivalent input.</p>
        <p><strong style="color:var(--text);">Integrated structure:</strong> Full LNG sale price at delivery point is the taxable revenue. Government take applies to the entire margin. Higher nominal take on a gross revenue basis but may include LNG-specific incentives (Papua New Guinea: 10-year CIT holiday; Qatar NDR: LNG royalty differentiated from oil).</p>
        <p><strong style="color:var(--text);">4-step IC comparison workflow:</strong> (1) Identify structure: integrated (exposed to liquefaction capex/opex) or tolling (fixed fee)? (2) Compute effective wellhead price under tolling: LNG spot minus transport minus tolling fee. (3) Run Scenario Builder at effective wellhead price (tolling) vs. full LNG netback (integrated). (4) IC memo: "Tolling: effective wellhead $[X]/MMBtu at $[Y] LNG spot &mdash; ORCA take [Z]%. Integrated: ORCA take [A]% on full LNG netback." Rule of thumb: $2/MMBtu tolling fee &asymp; $11/bbl oil equivalent &asymp; 5&ndash;8pp take reduction vs. integrated at $75/bbl.</p>
        <p><strong style="color:var(--text);">Source:</strong> ORCA v309 (Aug 2026). Papua New Guinea LNG Government Agreement 2009; Qatar NDRA Circular 2022; EY LNG Handbook 2024; S&amp;P Global Platts LNG Price Survey 2024; Wood Mackenzie LNG Fiscal Economics 2024. Cross-references: FAQ A231 (LNG fiscal overlay); FAQ A232 (LNG tolling agreements and IRR impact); FAQ A84 (gas-weighted country adjustment); FAQ A60 (gas vs. oil fiscal adjustments).</p>
      </div>
    </details>

"""

# Find the insertion point: right before the Back to top div that follows A280
insertion_point = '    <div style="text-align:right;margin-top:16px;padding-top:10px;border-top:1px solid var(--border);">\n      <a href="#tab-btn-tmeth"'

count = content.count(insertion_point)
print(f'Found {count} instances of insertion point')

if count == 1:
    content = content.replace(insertion_point, new_faqs + insertion_point, 1)
    with open(HTML, 'w', encoding='utf-8') as f:
        f.write(content)
    print('FAQs inserted successfully')
    new_content = open(HTML, encoding='utf-8').read()
    new_count = new_content.count('faq-A28')
    print(f'faq-A28x elements found: {new_count}')
else:
    print('ERROR: wrong count for insertion point')
    sys.exit(1)
